### ISSUE TITLE
NextCloud 11

### ISSUE THREAD

**Issue by philip-ulrich** [syncloud/nextcloud#1]
Hey guys. Any ETA on NextCloud 11 availability?

**Comment by taschenlampe** [comment]
I see that the script has been updated. What is the best way to update to NC11?

**Comment by cyberb** [comment]
I have tried to switch to v11, couple of tests failed on our build server, need couple days for making sure it can be released.
I will let you know when it is ready.

**Comment by cyberb** [comment]
We have just released v11, please go to settings and hit update. Then go to App Central and upgrade nextcloud.

Let us know here if you have any issues with the upgrade.

**Comment by taschenlampe** [comment]
Hi!
All went fine, great! Happy to use NC11.
 If I may add a little suggestion. Would it be possible to notify users that there is an update available? Would it be possible that there is a little info In the UI Settings showing what app is updatable? Clicking on the Icon would lead users to the App-Center where they can update the selected App? 
![nextcloud-128_update](https://cloud.githubusercontent.com/assets/10836480/21467856/8da9805e-c9fb-11e6-8615-2f727d5b7bee.png)
![update_available](https://cloud.githubusercontent.com/assets/10836480/21467889/ce6e811a-c9fc-11e6-9e0f-449d39f1f4c5.png)

**Comment by cyberb** [comment]
We are already thinking about changing updates process here: https://github.com/syncloud/platform/issues/202 and we will take your suggestion into consideration.
Thanks!
